FROM node:17-alpine as builder

WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code to the container
COPY . .

# Set NODE_ENV to development
ENV NODE_ENV=development

# # Copy .env.dev file to the container 
# COPY .env.dev .env

# Build the Vite application for development
RUN npm run build

# Use a lightweight Node.js image for the final image
FROM node:17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/dist /app/dist

# Install serve globally to serve the application
RUN npm install -g serve

# Expose the port that serve will use
EXPOSE 8080

# Start the application using serve
CMD ["serve", "-s", "dist"]
